"""add_promotions_tax_foundation

Revision ID: 4431733062ed
Revises: 0011_delivery_foundation
Create Date: 2026-10-05 22:24:10.136815
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4431733062ed'
down_revision: str | None = '0011_delivery_foundation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', 'BUY_X_GET_Y', name='discount_type_enum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('min_order_amount_minor', sa.Integer(), nullable=True),
    sa.Column('max_discount_minor', sa.Integer(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_customer', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'EXHAUSTED', name='coupon_status_enum'), nullable=False),
    sa.Column('applicable_categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('applicable_product_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('applicable_variant_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_product_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_variant_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('first_order_only', sa.Boolean(), nullable=False),
    sa.Column('new_customers_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(discount_type = 'PERCENTAGE' AND discount_value <= 100) OR discount_type != 'PERCENTAGE'", name=op.f('ck_coupons_ck_coupons_percentage_max_100')),
    sa.CheckConstraint('discount_value > 0', name=op.f('ck_coupons_ck_coupons_positive_discount')),
    sa.CheckConstraint('max_discount_minor IS NULL OR max_discount_minor > 0', name=op.f('ck_coupons_ck_coupons_positive_max_discount')),
    sa.CheckConstraint('max_uses IS NULL OR max_uses > 0', name=op.f('ck_coupons_ck_coupons_positive_max_uses')),
    sa.CheckConstraint('max_uses_per_customer IS NULL OR max_uses_per_customer > 0', name=op.f('ck_coupons_ck_coupons_positive_max_uses_per_customer')),
    sa.CheckConstraint('min_order_amount_minor IS NULL OR min_order_amount_minor >= 0', name=op.f('ck_coupons_ck_coupons_nonnegative_min_order')),
    sa.CheckConstraint('valid_from <= valid_until', name=op.f('ck_coupons_ck_coupons_valid_window')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name='uq_coupons_code'),
    sa.UniqueConstraint('code', name=op.f('uq_coupons_code'))
    )
    op.create_index('ix_coupons_active_window', 'coupons', ['status', 'valid_from', 'valid_until'], unique=False)
    op.create_index('ix_coupons_status', 'coupons', ['status'], unique=False)
    op.create_index('ix_coupons_validity', 'coupons', ['valid_from', 'valid_until'], unique=False)
    op.create_table('tax_jurisdictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_jurisdictions')),
    sa.UniqueConstraint('postal_code', name='uq_tax_jurisdictions_postal')
    )
    op.create_index('ix_tax_jurisdictions_state', 'tax_jurisdictions', ['state_code'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('ALCOHOL', 'BEVERAGE_NON_ALCOHOLIC', 'MIXER', 'SNACK', 'ICE', 'PARTY_SUPPLY', 'RECOVERY', name='tax_category_enum'), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=False),
    sa.Column('cgst_rate_bps', sa.Integer(), nullable=False),
    sa.Column('sgst_rate_bps', sa.Integer(), nullable=False),
    sa.Column('igst_rate_bps', sa.Integer(), nullable=False),
    sa.Column('cess_rate_bps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cess_rate_bps >= 0', name=op.f('ck_tax_rates_ck_tax_rates_cess_nonnegative')),
    sa.CheckConstraint('cgst_rate_bps >= 0 AND cgst_rate_bps <= 10000', name=op.f('ck_tax_rates_ck_tax_rates_cgst_range')),
    sa.CheckConstraint('igst_rate_bps >= 0 AND igst_rate_bps <= 10000', name=op.f('ck_tax_rates_ck_tax_rates_igst_range')),
    sa.CheckConstraint('rate_bps >= 0 AND rate_bps <= 10000', name=op.f('ck_tax_rates_ck_tax_rates_rate_range')),
    sa.CheckConstraint('sgst_rate_bps >= 0 AND sgst_rate_bps <= 10000', name=op.f('ck_tax_rates_ck_tax_rates_sgst_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_rates')),
    sa.UniqueConstraint('state_code', 'category', name='uq_tax_rates_state_category')
    )
    op.create_index('ix_tax_rates_category', 'tax_rates', ['category'], unique=False)
    op.create_index('ix_tax_rates_state', 'tax_rates', ['state_code'], unique=False)
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_earned', sa.Integer(), nullable=False),
    sa.Column('lifetime_redeemed', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('tier_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lifetime_earned >= 0', name=op.f('ck_loyalty_accounts_ck_loyalty_accounts_nonnegative_lifetime')),
    sa.CheckConstraint('points_balance >= 0', name=op.f('ck_loyalty_accounts_ck_loyalty_accounts_nonnegative_balance')),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_loyalty_accounts_customer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_accounts')),
    sa.UniqueConstraint('customer_id', name='uq_loyalty_accounts_customer')
    )
    op.create_index('ix_loyalty_accounts_tier', 'loyalty_accounts', ['tier'], unique=False)
    op.create_table('coupon_usages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('discount_applied_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_usages_coupon_id_coupons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_coupon_usages_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_usages_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_usages')),
    sa.UniqueConstraint('coupon_id', 'customer_id', 'order_id', name='uq_coupon_usage')
    )
    op.create_index('ix_coupon_usages_coupon', 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index('ix_coupon_usages_customer', 'coupon_usages', ['customer_id'], unique=False)
    op.create_index('ix_coupon_usages_order', 'coupon_usages', ['order_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EARN', 'REDEEM', 'EXPIRE', 'ADJUST', name='loyalty_transaction_type_enum'), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_delta != 0', name=op.f('ck_loyalty_transactions_ck_loyalty_transactions_nonzero_delta')),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], name=op.f('fk_loyalty_transactions_account_id_loyalty_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_loyalty_transactions_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_transactions'))
    )
    op.create_index('ix_loyalty_transactions_account', 'loyalty_transactions', ['account_id'], unique=False)
    op.create_index('ix_loyalty_transactions_created', 'loyalty_transactions', ['created_at'], unique=False)
    op.create_index('ix_loyalty_transactions_order', 'loyalty_transactions', ['order_id'], unique=False)
    op.create_index('ix_loyalty_transactions_type', 'loyalty_transactions', ['transaction_type'], unique=False)
    op.drop_constraint(op.f('uq_deliveries_order_id'), 'deliveries', type_='unique')
    op.create_unique_constraint('uq_deliveries_order', 'deliveries', ['order_id'])
    op.drop_index(op.f('uq_delivery_slots_location_start'), table_name='delivery_slots')
    op.create_unique_constraint('uq_delivery_slots_location_start', 'delivery_slots', ['fulfillment_location_id', 'start_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_delivery_slots_location_start', 'delivery_slots', type_='unique')
    op.create_index(op.f('uq_delivery_slots_location_start'), 'delivery_slots', ['fulfillment_location_id', 'start_at'], unique=True)
    op.drop_constraint('uq_deliveries_order', 'deliveries', type_='unique')
    op.create_unique_constraint(op.f('uq_deliveries_order_id'), 'deliveries', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_loyalty_transactions_type', table_name='loyalty_transactions')
    op.drop_index('ix_loyalty_transactions_order', table_name='loyalty_transactions')
    op.drop_index('ix_loyalty_transactions_created', table_name='loyalty_transactions')
    op.drop_index('ix_loyalty_transactions_account', table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index('ix_coupon_usages_order', table_name='coupon_usages')
    op.drop_index('ix_coupon_usages_customer', table_name='coupon_usages')
    op.drop_index('ix_coupon_usages_coupon', table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index('ix_loyalty_accounts_tier', table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index('ix_tax_rates_state', table_name='tax_rates')
    op.drop_index('ix_tax_rates_category', table_name='tax_rates')
    op.drop_table('tax_rates')
    op.drop_index('ix_tax_jurisdictions_state', table_name='tax_jurisdictions')
    op.drop_table('tax_jurisdictions')
    op.drop_index('ix_coupons_validity', table_name='coupons')
    op.drop_index('ix_coupons_status', table_name='coupons')
    op.drop_index('ix_coupons_active_window', table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
